export const medicalSpecializations = [
    { name: "Anesthesiology" },
    { name: "Cardiology" },
    { name: "Dermatology" },
    { name: "Emergency Medicine" },
    { name: "Endocrinology" },
    { name: "Family Medicine" },
    { name: "Gastroenterology" },
    { name: "General Surgery" },
    { name: "Hematology" },
    { name: "Infectious Disease" },
    { name: "Internal Medicine" },
    { name: "Nephrology" },
    { name: "Neurology" },
    { name: "Obstetrics and Gynecology (OB/GYN)" },
    { name: "Oncology" },
    { name: "Ophthalmology" },
    { name: "Orthopedic Surgery" },
    { name: "Otolaryngology (ENT)" },
    { name: "Pediatrics" },
    { name: "Physical Medicine and Rehabilitation" },
    { name: "Plastic Surgery" },
    { name: "Psychiatry" },
    { name: "Pulmonology" },
    { name: "Radiology" },
    { name: "Rheumatology" },
    { name: "Urology" }
  ];